### ISSUE TITLE
[topic lin & win] Memory leak discovered when using gst-launch-1.0 videotestsrc ! mfxsink 

### ISSUE THREAD

**Issue by kuhanh91** [intel/gstreamer-media-SDK#62] opened 2017-12-08 03:30 UTC
gstreamer framework: 1.12.3
gst-msdk : topic_linux_and_window
environment: wayland weston

The command used: gst-launch-1.0 videotestsrc ! mfxsink
 
First test run for 12 hours: RES increased from 21760 to 162988
Second test run for 2 hours: RES increased from 21740 to 40012

This issue was previously fixed in master branch with the commit id 857381e (present in topic branch as well).

[HSD-ES: 1504448857]

**Comment by SiewHoon** [comment] 2017-12-08 04:12
Try on this code changed suggest by Ishmael ( ishmael1985/gstreamer-media-SDK@0223ebb ), see RES still continue increase or not.

**Comment by kuhanh91** [comment] 2017-12-08 08:21
I have tried the suggested code change above and still observe the RES increasing overtime.

Test run for almost 2 hours: RES increased from 21172 to 36144

**Comment by ishmael1985** [comment] 2017-12-08 10:44
The suggested fix is targeted for issue #57 , which I need you to confirm if it does reduce the overall memory leak, for this issue I will investigate further.

**Comment by ishmael1985** [comment] 2017-12-08 15:27
This code is sync'ed with the master branch, is it possible that the master branch has the same issue as well?

**Comment by kuhanh91** [comment] 2017-12-14 02:12
I double checked the topic branch for the commit id 857381e at the file gst-libs/mfx/wayland/gstmfxwindow_wayland.c and the changes from commit id 857381e are present. 

I also cherry-picked the commit id 5392929 from issue #57 and run this command on topic branch. The RES is still observed to increase over time. One hour of running the command and RES increased from 22852 to 31480.

I tested with master branch and the issue is not reproducible. A 12 hour run of the command on master branch shows consistent RES usage, RES consistently around ~20796 to ~21000 throughout the execution of the command.

**Comment by ishmael1985** [comment] 2017-12-14 05:25
I haven't addressed this issue yet. I believe even for X11 there is a memory leak with the topic branch under the same command. Please verify.
It would be useful if you could obtain the Valgrind GST tracer logs for this command under the topic branch so that I can better identify the memory leak. Just showing me the RES is going up doesn't help.
Issue #57 should have been resolved by https://github.com/intel/gstreamer-media-SDK/commit/53929290a39e7917f8fe55d2a3fa1db04de0b637, please verify if that is the case by comparing X11 and Wayland memory usage for the gst-play-1.0 playlist case.

**Comment by kuhanh91** [comment] 2017-12-19 08:10
I tested this with commit id 5392929 and 53cc6d1 from issue #60 applied to topic branch.

I tried obtaining the valgrind logs but the following errors appears repeatedly and the video stutters similar to drops in fps:

WARNING: from element /GstPipeline:pipeline0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2901): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0:
There may be a timestamping problem, or this computer is too slow.

Attaching the valgrind logs:
[valgrind_issue_62.log](https://github.com/intel/gstreamer-media-SDK/files/1570806/valgrind_issue_62.log)
[valgrind_issue_62_2.log](https://github.com/intel/gstreamer-media-SDK/files/1570807/valgrind_issue_62_2.log)

I tried reinstalling gst-msdk and also rebooting the system multiple times but still hits the error above if i run valgrind with the command.

I also tried to obtain GST tracer logs with the following command: GST_DEBUG="GST_TRACER:7" GST_TRACERS="leaks" GST_DEBUG_FILE=trace.log gst-launch-1.0 videotestsrc ! mfxsink but it did not show any further messages than the initial ones. Attaching the trace.log.
[trace.log](https://github.com/intel/gstreamer-media-SDK/files/1570817/trace.log)

What would be a suitable GST_DEBUG option that I should use? GST_DEBUG=7 outputs a huge number of logs, would that be helpful?

**Comment by ishmael1985** [comment] 2017-12-19 08:42
I've taken a look at this bug, for periodic intervals, there is a loss of ~260-264 bytes no matter what render resolution is used, both X11 and Wayland. It happens faster in Wayland though compared to X11.
I've checked the valgrind logs and there seems to be no indication from libgstmfx.so of a leak related to this bug. GST_TRACER doesn't indicate any unreleased GstObjects, so it's not helpful indeed.
Try getting the valgrind logs with mfxsink sync=false, please make sure you capture the logs when the leaks are being observed so that we can pinpoint where the leak is exactly happening.

**Comment by kuhanh91** [comment] 2017-12-21 07:43
With mfxsink sync=false, it does not lag and the following error message which appears while running without mfxsink sync=false does not occur:
WARNING: from element /GstPipeline:pipeline0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2901): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0:
There may be a timestamping problem, or this computer is too slow.

With mfxsink sync=false and tested in X11, the valgrind logs is: [valgrind_issue_62_X11.log](https://github.com/intel/gstreamer-media-SDK/files/1578312/valgrind_issue_62_X11.log)

Without mfxsink sync=false and tested in X11, the valgrind logs is: [valgrind_issue_62_X11_without_sync_false.log](https://github.com/intel/gstreamer-media-SDK/files/1578314/valgrind_issue_62_X11_without_sync_false.log)

In both logs, similar definite lost logs are observed:
==3027==    by 0x81C4C1D: MFX::mfx_dll_free(void*) (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C3B4D: MFX_DISP_HANDLE::UnLoadSelectedDLL() (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C3B98: MFX_DISP_HANDLE::Close() (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C0BE1: MFXClose (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C4022: MFX_DISP_HANDLE::LoadSelectedDLL(char const*, eMfxImplType, int, int, mfxInitParam&) (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C13F3: MFXInitEx (in /usr/lib/gstreamer-1.0/libgstmfx.so)
==3027==    by 0x81C264A: MFXInit (in /usr/lib/gstreamer-1.0/libgstmfx.so)

The similar thing is seen in wayland valgrind logs and also in the valgrind logs of issue #57 (both wayland and X11).

Should be noted that the video lags while using valgrind and without mfxsink sync=false in both wayland and X11.

**Comment by ishmael1985** [comment] 2017-12-21 08:13
I've noted the issues and been able to reproduce them, since the leaks are similar, it is highly unlikely the leak comes from the mfxsink renderer. I've gotten the same leak even with glimagesink using the EGL backend.
The libgstmfx.so errors should not be a concern here as they only involve the initialization and destruction of MFX sessions, the leak occurs while the pipeline is running...

**Comment by ishmael1985** [comment] 2017-12-31 17:25
Please get the latest update on my master branch for a final fix on this issue.
https://github.com/ishmael1985/gstreamer-media-SDK

**Comment by ishmael1985** [comment] 2018-02-26 10:38
@kuhanh91 since this issue has been resolved can this be closed?

**Comment by SiewHoon** [comment] 2018-02-28 07:55
Don't want to mix up with another #57 issue with the memory leak detected by valgrind tools. I will closed this issue. The RES keep increasing will track  in #57.

**Closed by SiewHoon** 2018-02-28 07:55 UTC
Labels: bug

**Comment by eero-t** [comment] 2018-11-09 10:48
> What makes this issue hard to debug is that there are no other libgstmfx.so leaks detected with Valgrind.

When leak isn't large enough to be visible with Valgrind Massif, nor lost pointer found with Valgrind Memcheck, I've used sp-rtrace to track leaks down:
  https://github.com/maemo-tools-old/sp-rtrace

With it one can track leaks of specific sizes, if wanted.

(There's also variant called "functracer" in same project, which can attach to already running processes that start leaking only after long time of running, but I'm not sure whether that still works with latest Linux versions.  It was using ptrace do do similar things as kernel kprobes do nowadays.)
