### ISSUE TITLE
va_openDriver() returns -1 on Apollo Lake Chip after gstreamer-media-sdk install

### ISSUE THREAD

**Issue by skyline220** [intel/gstreamer-media-SDK#115] opened 2018-07-18 04:24 UTC
Hardware: UP Squared Maker Board (Intel Pentium N4200 Processor)

OS: Ubuntu 16.04 LTS
Kernel: 4.14.16 Upgraded according to: https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack

Install completed using this repo.

**gst-inspect-1.0 mfxvpp**
Command Succeeds

**gst-inspect-1.0 mfxdecode**
Command Succeeds

**gst-launch-1.0 filesrc location=/path/to/BigBuckBunny_320x180.mp4 ! qtdemux ! h264parse ! mfxdecode ! fpsdisplaysink video-sink=mfxsink**

Command Returns Error with:
Setting pipeline to PAUSED ...
libva info: VA-API version 1.2.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Additional debug info:
gstbasesink.c(5245): gst_base_sink_change_state (): /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstMfxSinkBin:mfxsinkbin0/GstMfxSink:mfxsink0:
Failed to start
Setting pipeline to NULL ...
Freeing pipeline ...

What's stranger is vainfo worked during the media-driver installation step and displayed:

libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.0 (libva 2.0.1.pre1)
vainfo: Driver version: Intel iHD driver - 2.0.0
vainfo: Supported profile and entrypoints
(then all entrypoints are listed VAProfileNone                   : VAEntrypointVideoProc etc..)

Please provide any assistance you can, thanks!

**Comment by skyline220** [comment] 2018-07-18 21:17
Hi Ismael,

Yes this command does work:
vainfo --display drm --device /dev/dri/renderD128

Returns:
libva info: VA-API version 1.2.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_2
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.2 (libva 2.2.1.pre1)
vainfo: Driver version: Intel iHD driver - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD

Please let me know how I could proceed and thanks for your help.

**Comment by ishmael1985** [comment] 2018-07-18 21:19
Tried sample_decode?

**Comment by skyline220** [comment] 2018-07-20 23:16
Hi Ishmael,

After running the command: vainfo --display drm --device /dev/dri/renderD128
as you suggested Gst MFX plugins work! I dont even need to export the Libva environment variables, does this make sense? More specifically does that vainfo --display drm command actually change any settings or is it just for displaying info?

Thanks

**Comment by ishmael1985** [comment] 2018-07-20 23:19
I wanted to just pinpoint the cause of your problem, but I guess I have a magic touch :)
Well then, you may close this issue.

**Comment by skyline220** [comment] 2018-07-20 23:59
Okay thanks, maybe just not exporting the variables worked too? Either way thanks for your help.

**Closed** 2018-07-21 00:00 UTC
