### ISSUE TITLE
mfxhevcenc poor performace

### ISSUE THREAD

**Issue by Nastooh-Inca** [intel/gstreamer-media-SDK#140] opened 2018-12-17 20:45 UTC
On ubuntu 16.04, setup as https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack, with Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz processor, I am getting poor results when encoding with mfxhevcenc (see gst-launch below).

 I have tried both the tip of the master (hash 1aae2ee9e36763e9dacec72) and topic_linux_and_window (hash 1a36912b25cfacedd04aba913)
```
gst-launch-1.0    -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10  ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc ! queue ! h265parse ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1
```
This is in contrast to gstreamer 1.14 msdk library, i.e., 
```
gst-launch-1.0    -vm  videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10  ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! msdkh265enc  ! queue ! h265parse ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1
```
where output stream is crisp and clear. (See attached files.)
Any thoughts?
Cheers,
![mfxhevcenc](https://user-images.githubusercontent.com/30271952/50114467-6dac3e80-01f9-11e9-8eac-02773949d217.jpg)
![msdkh265enc](https://user-images.githubusercontent.com/30271952/50114476-7270f280-01f9-11e9-8f6e-b6670666425d.jpg)

**Comment by ishmael1985** [comment] 2018-12-19 22:31
What do you get if you simplify the mfxhevcenc pipeline by removing h265parse from it, i.e.

gst-launch-1.0    -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10  ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1

**Comment by Nastooh-Inca** [comment] 2018-12-19 22:54
Thank you for your reply. I still get intermittent loss:
![image](https://user-images.githubusercontent.com/30271952/50253058-cfa5a900-039d-11e9-9d8e-8ceaa0926836.png)
There are; however, periods of clear video, lasting few seconds.
Cheers,

**Comment by ishmael1985** [comment] 2018-12-19 23:11
If you try putting back h265parse followed by a capsfilter 'video/x-h265, stream-format=byte-stream' and then setting the encoder async-depth to 1 as shown by the following pipeline, what do you get?

gst-launch-1.0    -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10  ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc async-depth=1 ! 'video/x-h265, stream-format=byte-stream' ! queue ! h265parse ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1

**Comment by Nastooh-Inca** [comment] 2018-12-19 23:16
A greyish blob, similar to the 1st picture, and ffplay is complaining of missing POC:
```
[hevc @ 0x7f32880008c0] Could not find ref with POC 0    0B f=0/0   
[hevc @ 0x7f32880008c0] Could not find ref with POC 4
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
Input #0, mpegts, from 'udp://239.141.50.1:1234': sq=    0B f=0/0   
  Duration: N/A, start: 3608.633311, bitrate: N/A
  Program 1 
    Stream #0:0[0x64]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 30 tbc
[hevc @ 0x7f32880395a0] Could not find ref with POC 0
[hevc @ 0x7f32880395a0] Could not find ref with POC 4    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/10   
[hevc @ 0x7f3288359c60] Could not find ref with POC 4    0B f=0/11   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/15   
[hevc @ 0x7f3288106c20] Could not find ref with POC 4    0B f=0/25   
[hevc @ 0x7f328809d360] Could not find ref with POC 4    0B f=0/39   
[hevc @ 0x7f32880aece0] Could not find ref with POC 4    0B f=0/53   
[mpegts @ 0x7f3288009240] PES packet size mismatchsq=    0B f=0/56   
```
Cheers,

**Comment by Nastooh-Inca** [comment] 2018-12-19 23:46
Same as before. Theses are ffplay messages:
```
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
Input #0, mpegts, from 'udp://239.141.50.1:1234': sq=    0B f=0/0   
  Duration: N/A, start: 3644.366644, bitrate: N/A
  Program 1 
    Stream #0:0[0x64]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 30 tbc
[hevc @ 0x7f018809f160] Could not find ref with POC 12   0B f=0/0   
[hevc @ 0x7f018809f160] Could not find ref with POC 10
[hevc @ 0x7f018809f160] Could not find ref with POC 8
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f0188009240] PES packet size mismatchsq=    0B f=0/0   
```
Cheers,

**Comment by ishmael1985** [comment] 2018-12-19 23:49
Ok. How about this?

`gst-launch-1.0 -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10 ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc ! 'video/x-h265, stream-format=byte-stream' ! queue ! h265parse ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1`

**Comment by Nastooh-Inca** [comment] 2018-12-19 23:54
No dice:
```
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/0   
Input #0, mpegts, from 'udp://239.141.50.1:1234': sq=    0B f=0/0   
  Duration: N/A, start: 3608.966644, bitrate: N/A
  Program 1 
    Stream #0:0[0x64]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 30 tbc
[hevc @ 0x7f9a440ba4a0] Could not find ref with POC 8
[hevc @ 0x7f9a440ba4a0] Could not find ref with POC 10
[hevc @ 0x7f9a440ba4a0] Could not find ref with POC 12   0B f=0/0   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/1   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/2   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/2   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/5   
[hevc @ 0x7f9a442beb20] Could not find ref with POC 4    0B f=0/7   
[mpegts @ 0x7f9a44009240] PES packet size mismatchsq=    0B f=0/9   
```
Cheers,

**Comment by ishmael1985** [comment] 2018-12-20 00:42
I think I know what happened. Try this:

`gst-launch-1.0 -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10 ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc rate-control=cbr bitrate=2048 ! queue ! muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1`

**Comment by Nastooh-Inca** [comment] 2018-12-20 17:01
Running the above, as is, does reduce the observed glitches. However, does not eliminate them, e.g., ffplay is reporting:
```
3661.26 M-V:  0.024 fd=   0 aq=    0KB vq= 1275KB sq=    0B f=0/0   
3661.29 M-V:  0.024 fd=   0 aq=    0KB vq= 1273KB sq=    0B f=0/0   
[hevc @ 0x7f47480d7aa0] The cu_qp_delta 34 is outside the valid range [-26, 25].
[mpegts @ 0x7f4748009240] PES packet size mismatchsq=    0B f=0/0   
[hevc @ 0x7f47480d7aa0] The cu_qp_delta -130 is outside the valid range [-26, 25].
[hevc @ 0x7f47480d7aa0] The cu_qp_delta 50 is outside the valid range [-26, 25].
```
Strangely enough, increasing the bit rate to 4096 worsens the situation, with frequent video breakdowns.
```
[hevc @ 0x7f47482fcac0] Duplicate POC in a sequence: 4.  0B f=1/7   
[hevc @ 0x7f47482fcac0] Error parsing NAL unit #2.
[hevc @ 0x7f47480d7aa0] Duplicate POC in a sequence: 2.  0B f=1/8   
[hevc @ 0x7f47480d7aa0] Error parsing NAL unit #2.
[hevc @ 0x7f4748031780] Duplicate POC in a sequence: 5.  0B f=1/8   
[hevc @ 0x7f4748031780] Error parsing NAL unit #2.
[hevc @ 0x7f474805f9c0] Could not find ref with POC 6    0B f=1/8   
[hevc @ 0x7f47482fcac0] Duplicate POC in a sequence: 4.  0B f=1/8   
[hevc @ 0x7f47482fcac0] Error parsing NAL unit #2.
[hevc @ 0x7f474805f9c0] Could not find ref with POC 6    0B f=1/9   
[hevc @ 0x7f47482fcac0] Duplicate POC in a sequence: 4.  0B f=1/9   
[hevc @ 0x7f47482fcac0] Error parsing NAL unit #2.
[hevc @ 0x7f47480d7aa0] Could not find ref with POC 6    0B f=1/10   
[hevc @ 0x7f474805f9c0] Duplicate POC in a sequence: 4.  0B f=1/10   
```
Cheers,

**Comment by Nastooh-Inca** [comment] 2018-12-20 23:49
And problem was due to transport rate, not encoder per se, i.e., adding max-bitrate to udpsink, so far, has solved the problem:
```
gst-launch-1.0 -vm --gst-plugin-path=./gstreamer-media-SDK/build/gst/mfx videotestsrc is-live=true pattern=zone-plate kx2=20 ky2=20 kxy=4 kt2=10 ! queue ! video/x-raw, format=I420,width=1920,height=1080 ! queue ! videoconvert ! queue ! mfxhevcenc  rate-control=cbr bitrate=10000 gop-size=32 idr-interval=1  async-depth=1 gop-distance=4 ! queue !  muxer.sink_100 mpegtsmux name=muxer prog-map=program_map,sink_100=1 ! queue ! tsparse ! queue ! udpsink name=udpsink port=1234 host=239.141.50.1 max-bitrate=120000000
```
Cheers,

**Comment by ishmael1985** [comment] 2018-12-21 19:43
@Nastooh-Inca that's cool. I had a look at the gst-msdk code in gst-plugins-bad and they used a different default encoder setting from gst-mfx. The mfxhevcenc properties in the last pipeline I provided used gst-msdk default encoder settings but maybe I missed a setting or two. But it's not the gst-mfx code itself.

Glad to know you fixed your issue :) Please close this if the issue is considered resolved on your side.

**Closed** 2018-12-21 19:55 UTC
